enpal_assessment_project:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: admin
      port: 5432
      schema: dev
      threads: 1
      type: postgres
      user: admin
    prod:
      dbname: postgres
      host: localhost
      pass: admin
      port: 5432
      schema: prod
      threads: 1
      type: postgres
      user: admin
    ci:
      dbname: postgres
      host: localhost
      pass: admin
      port: 5432
      schema: ci
      threads: 1
      type: postgres
      user: admin
    sandbox:
      dbname: postgres
      host: localhost
      pass: admin
      port: 5432
      schema: sandbox_mahmud
      threads: 1
      type: postgres
      user: admin
  target: dev
