version: 2

models:
  - name: stg_pipedrive_deal_activities
    description: "Staging model for pipedrive deal activities"
    columns:
      - name: deal_activity_id
        data_type: integer
        description: "Unique identifier for each deal activity"

      - name: deal_activity_type
        data_type: character varying
        description: "Type of deal activity"

      - name: deal_activity_assigned_to_user
        data_type: integer
        description: "The user ID that the deal activity is assigned to"

      - name: deal_id
        data_type: integer
        description: "The ID of the deal that the activity is associated with"

      - name: is_deal_activity_done
        data_type: boolean
        description: "Whether the deal activity is marked as done"

      - name: deal_activity_due_to
        data_type: timestamp without time zone
        description: "The due date for the deal activity"

  - name: stg_pipedrive_deal_activity_types
    description: " Staging model for pipedrive deal activity types"
    columns:
      - name: deal_activity_type_id
        data_type: integer
        description: "Unique identifier for each deal activity type"

      - name: deal_activity_type_name
        data_type: character varying
        description: "The name of the deal activity type"

      - name: deal_activity_type_stage
        data_type: text
        description: "The stage that the deal activity type belongs to"

      - name: is_deal_activity_type_active
        data_type: boolean
        description: "Whether the deal activity type is active or not"

      - name: deal_activity_type
        data_type: character varying
        description: " The type of the deal activity type"
  
  - name: stg_pipedrive_deal_changes
    description: " Staging model for pipedrive deal changes. This model captures the history of changes made to deals, including stage changes, user assignments, and lost reasons."
    columns:
      - name: deal_id
        data_type: integer
        description: "The ID of the deal that was changed"

      - name: change_time
        data_type: timestamp without time zone
        description: "The timestamp when the deal was changed"
      - name: stage_id
        data_type: integer
        description: " The ID of the stage that the deal was moved to (if applicable)"

      - name: user_id
        data_type: integer
        description: "The ID of the user who made the change"

      - name: deal_created_at
        data_type: timestamp without time zone
        description: "The timestamp when the deal was created"

      - name: deal_lost_reason_id
        data_type: integer
        description: " The ID of the lost reason if the deal was marked as lost (if applicable)"

  - name: stg_pipedrive_deal_fields
    description: " Staging model for pipedrive deal fields. This model captures the custom fields associated with deals, including their IDs, keys, names, and value options. The value options are stored as a JSONB data type to accommodate the varying structures of custom field options."
    columns:
      - name: deal_field_id
        data_type: integer
        description: "Unique identifier for each deal field"

      - name: deal_field_key
        data_type: character varying
        description: "The key of the deal field"


      - name: deal_field_name
        data_type: character varying
        description: " The name of the deal field"

      - name: deal_field_value_options
        data_type: jsonb
        description: "The value options for the deal field, stored as JSONB to accommodate varying structures"
  
  - name: stg_pipedrive_deal_lost_reason
    description: " Staging model for pipedrive deal lost reasons. This model extracts the lost reasons for deals from the custom fields and flattens them into a tabular format. Each lost reason is represented by its ID and the corresponding label, allowing for easier analysis of why deals were lost."
    columns:
      - name: lost_reason_id
        data_type: integer
        description: "The ID of the lost reason, extracted from the deal field options"

      - name: actual_lost_reason
        data_type: text
        description: "The actual lost reason value extracted from the deal field options"
  
  - name: stg_pipedrive_deal_stages
    description: " Staging model for pipedrive deal stages. This model captures the different stages that deals can go through in the sales pipeline, including their IDs and names. This information is crucial for analyzing deal progression and understanding where deals are in the sales funnel."
    columns:
      - name: deal_stage_id
        data_type: integer
        description: " The ID of the deal stage, extracted from the stages table"

      - name: deal_stage_name
        data_type: character varying
        description: "The name of the deal stage, extracted from the stages table"
  
  - name: stg_pipedrive_deal_users
    description: " Staging model for pipedrive deal users. This model captures the users associated with deals, including their IDs, names, and email addresses. This information is essential for analyzing user assignments to deals and understanding the roles of different users in the sales process."
    columns:
      - name: deal_user_id
        data_type: integer
        description: " The ID of the user, extracted from the users table"

      - name: deal_user_name
        data_type: character varying
        description: "The name of the user, extracted from the users table"

      - name: deal_user_email
        data_type: character varying
        description: "The email address of the user, extracted from the users table"

      - name: deal_user_last_modified
        data_type: timestamp without time zone
        description: "The timestamp when the user information was last modified"